export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_KEY = 'GET_KEY';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHECK_TOKEN_STATUS = 'CHECK_TOKEN_STATUS';

// posts
export const GET_POSTS = 'GET_POSTS';
export const POST_ERROR = 'POST_ERROR';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_POST = 'GET_POST';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

// rivers
export const GET_RIVERS = 'GET_RIVERS';
export const RIVERS_ERROR = 'RIVERS_ERROR';
export const GET_RIVER = 'GET_RIVER';
export const NEW_RIVER = 'NEW_RIVER';
export const RIVER_PHOTOS = 'RIVER_PHOTOS';
export const DELETE_RIVERS = 'DELETE_RIVERS';
export const GET_RIVER_BY_ID = 'GET_RIVER_BY_ID';
export const DELETE_SINGLE_PHOTO = 'DELETE_SINGLE_PHOTO';
export const UPDATE_ADD_PHOTOS = 'UPDATE_ADD_PHOTOS';
export const SAVE_MAP = 'SAVE_MAP';
export const ADD_COMMENT_RIVER = 'ADD_COMMENT_RIVER';
export const DELETE_COMMENT_RIVER = 'DELETE_COMMENT_RIVER';
export const RIVER_COMMENT_UPDATE_LIKES = 'RIVER_COMMENT_UPDATE_LIKES';
export const CHANGE_PUBLISH_STATUS = 'CHANGE_PUBLISH_STATUS';
export const UPDATE_UPVOTE = 'UPDATE_UPVOTE';
export const UPDATE_DOWNVOTE = 'UPDATE_DOWNVOTE';

// user role
export const ADMIN_APPLICATION_SUBMIT = 'ADMIN_APPLICATION_SUBMIT';
export const ADMIN_APPLICATION_ERROR = 'ADMIN_APPLICATION_ERROR';
export const ADMIN_SET_ROLE = 'ADMIN_SET_ROLE';
export const ADMIN_CLEAR_ROLE = 'ADMIN_CLEAR_ROLE';
export const GET_APPLICATION_STATUS = 'GET_APPLICATION_STATUS';
export const CLEAR_USER_ROLE = 'CLEAR_USER_ROLE';
export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';
// master admin
export const APPLICATION_SET_STATUS = 'APPLICATION_SET_STATUS';
export const APPLICATION_GET_PENDING = 'APPLICATION_GET_PENDING';
export const APPLICATION_GET_APPROVED = 'APPLICATION_GET-APPROVED';
export const MASTER_ADMIN_ERROR = 'MASTER_ADMIN_ERROR';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const UPDATE_USER = 'UPDATE_USER';
